export const actionType = {
  // Auth
  SET_SIGN_IN: "SET_SIGN_IN",
  SET_SIGN_OUT: "SET_SIGN_OUT",
  SET_REGISTER: "SET_REGISTER",
  SET_ME: "SET_ME",

  // Banner
  SET_CAROUSEL: "SET_CAROUSEL",

  // Movie
  SET_MOVIE: "SET_MOVIE",
  PHIM_DANG_CHIEU: "PHIM_DANG_CHIEU",
  PHIM_SAP_CHIEU: "PHIM_SAP_CHIEU",

  // Cinema
  SET_CINEMA: "SET_CINEMA",
  CINEMA_ADDRESS: "CINEMA_ADDRESS",
  MOVIE_SCHEDULE: "MOVIE_SCHEDULE",
  CINEMA_DETAIL: "CINEMA_DETAIL",
  BOOK_TICKET: "BOOK_TICKET",

  // Loading
  IS_LOADING: "IS_LOADING"

  
};
